import { forwardRef, type ButtonHTMLAttributes, type InputHTMLAttributes, type ReactNode, type TextareaHTMLAttributes } from "react";
import { cn } from "@/lib/utils";

export function Button({ className, variant = "primary", ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "ghost" | "danger" }) {
  return <button className={cn("inline-flex items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-semibold transition disabled:pointer-events-none disabled:opacity-50", variant === "primary" && "bg-indigo-600 text-white shadow-sm hover:bg-indigo-700", variant === "secondary" && "border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200", variant === "ghost" && "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800", variant === "danger" && "bg-red-600 text-white hover:bg-red-700", className)} {...props} />;
}
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(({ className, ...props }, ref) => <input ref={ref} className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 dark:border-slate-700 dark:bg-slate-900 dark:focus:ring-indigo-950", className)} {...props} />); Input.displayName = "Input";
export const Textarea = forwardRef<HTMLTextAreaElement, TextareaHTMLAttributes<HTMLTextAreaElement>>(({ className, ...props }, ref) => <textarea ref={ref} className={cn("min-h-32 w-full resize-y rounded-xl border border-slate-200 bg-white p-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-indigo-400 focus:ring-4 focus:ring-indigo-100 dark:border-slate-700 dark:bg-slate-900 dark:focus:ring-indigo-950", className)} {...props} />); Textarea.displayName = "Textarea";
export function Card({ children, className }: { children: ReactNode; className?: string }) { return <div className={cn("rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900", className)}>{children}</div>; }
export function Badge({ children, tone = "slate" }: { children: ReactNode; tone?: "slate" | "green" | "amber" | "red" | "indigo" }) { const colors = { slate: "bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300", green: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300", amber: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300", red: "bg-red-100 text-red-700 dark:bg-red-950 dark:text-red-300", indigo: "bg-indigo-100 text-indigo-700 dark:bg-indigo-950 dark:text-indigo-300" }; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", colors[tone])}>{children}</span>; }
export function Progress({ value }: { value: number }) { return <div className="h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="h-full rounded-full bg-gradient-to-r from-indigo-600 to-blue-500 transition-all duration-500" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
